name: Project Metrics Weekly Generator

on:
  schedule:
    - cron: "59 23 * * 0" # Every Sunday at 23:59
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub matplotlib fpdf radon
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Generate report
        run: python Ishikawa_tools_generators/metrics/main.py
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: metrics-report
          path: ./Project_Metrics_Report.pdf
