name: Playwright Tests
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest-playwright
    - name: Install Playwright Browsers
      run: playwright install
    - name: Run Playwright tests
      run: pytest E2E/
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30